// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using writings_backend_dotnet.DB;

#nullable disable

namespace writings_backend_dotnet.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20241112180734_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Follow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("FollowedId")
                        .HasColumnType("uuid")
                        .HasColumnName("followed_id");

                    b.Property<Guid>("FollowerId")
                        .HasColumnType("uuid")
                        .HasColumnName("follower_id");

                    b.Property<DateTime>("OccurredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("occurred_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Accepted")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("FollowedId");

                    b.HasIndex("FollowerId", "FollowedId")
                        .IsUnique();

                    b.ToTable("follow", (string)null);
                });

            modelBuilder.Entity("FreezeR", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("ProceedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("proceed_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Frozen")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("freeze_r", (string)null);
                });

            modelBuilder.Entity("writings_backend_dotnet.Models.Block", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("BlockedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("blocked_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("BlockedId")
                        .HasColumnType("uuid")
                        .HasColumnName("blocked_id");

                    b.Property<Guid>("BlockerId")
                        .HasColumnType("uuid")
                        .HasColumnName("blocker_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reason");

                    b.HasKey("Id");

                    b.HasIndex("BlockedId");

                    b.HasIndex("BlockerId", "BlockedId")
                        .IsUnique();

                    b.ToTable("block", (string)null);
                });

            modelBuilder.Entity("writings_backend_dotnet.Models.Cache", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("ExpirationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(126)
                        .HasColumnType("character varying(126)");

                    b.HasKey("Id");

                    b.ToTable("cache", (string)null);
                });

            modelBuilder.Entity("writings_backend_dotnet.Models.Chapter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .HasColumnName("chapter_name");

                    b.Property<short>("Number")
                        .HasColumnType("smallint")
                        .HasColumnName("chapter_number");

                    b.Property<short>("SectionId")
                        .HasColumnType("smallint")
                        .HasColumnName("section_id");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("SectionId", "Number")
                        .IsUnique();

                    b.ToTable("chapter", (string)null);
                });

            modelBuilder.Entity("writings_backend_dotnet.Models.ChapterMeaning", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChapterId")
                        .HasColumnType("integer");

                    b.Property<short>("LanguageId")
                        .HasColumnType("smallint");

                    b.Property<string>("Meaning")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("chapter_meaning");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("ChapterId", "LanguageId")
                        .IsUnique();

                    b.ToTable("chapter_meaning", (string)null);
                });

            modelBuilder.Entity("writings_backend_dotnet.Models.Collection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasDefaultValue("")
                        .HasColumnName("name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.ToTable("collection", (string)null);
                });

            modelBuilder.Entity("writings_backend_dotnet.Models.CollectionVerse", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("CollectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("collection_id");

                    b.Property<string>("Note")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("note");

                    b.Property<DateTime>("SavedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("saved_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("VerseId")
                        .HasColumnType("integer")
                        .HasColumnName("verse_id");

                    b.HasKey("Id");

                    b.HasIndex("VerseId");

                    b.HasIndex("CollectionId", "VerseId")
                        .IsUnique();

                    b.ToTable("collection_verse", (string)null);
                });

            modelBuilder.Entity("writings_backend_dotnet.Models.Comment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("CommentNoteId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CommentVerseId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long?>("ParentCommentId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_comment_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ParentCommentId");

                    b.HasIndex("UserId");

                    b.ToTable("comment", (string)null);
                });

            modelBuilder.Entity("writings_backend_dotnet.Models.CommentNote", b =>
                {
                    b.Property<long>("CommentId")
                        .HasColumnType("bigint")
                        .HasColumnName("comment_id");

                    b.Property<int>("NoteId")
                        .HasColumnType("integer")
                        .HasColumnName("note_id");

                    b.HasKey("CommentId");

                    b.HasIndex("NoteId");

                    b.ToTable("comment_note", (string)null);
                });

            modelBuilder.Entity("writings_backend_dotnet.Models.CommentVerse", b =>
                {
                    b.Property<long>("CommentId")
                        .HasColumnType("bigint")
                        .HasColumnName("comment_id");

                    b.Property<int>("VerseId")
                        .HasColumnType("integer")
                        .HasColumnName("verse_id");

                    b.HasKey("CommentId");

                    b.HasIndex("VerseId");

                    b.ToTable("comment_verse", (string)null);
                });

            modelBuilder.Entity("writings_backend_dotnet.Models.FootNote", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("FootNoteTextId")
                        .HasColumnType("bigint")
                        .HasColumnName("footnote_text_id");

                    b.Property<short>("Index")
                        .HasColumnType("smallint")
                        .HasColumnName("index");

                    b.Property<short>("Number")
                        .HasColumnType("smallint")
                        .HasColumnName("number");

                    b.Property<long>("TranslationTextId")
                        .HasColumnType("bigint")
                        .HasColumnName("translation_text_id");

                    b.HasKey("Id");

                    b.HasIndex("FootNoteTextId");

                    b.HasIndex("TranslationTextId");

                    b.HasIndex("Number", "FootNoteTextId", "Index");

                    b.ToTable("footnote", (string)null);
                });

            modelBuilder.Entity("writings_backend_dotnet.Models.FootNoteText", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.HasKey("Id");

                    b.ToTable("footnote_text", (string)null);
                });

            modelBuilder.Entity("writings_backend_dotnet.Models.Language", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("LangCode")
                        .IsRequired()
                        .HasColumnType("varchar(2)");

                    b.Property<string>("LangEnglish")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("LangOwn")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("LangCode")
                        .IsUnique();

                    b.ToTable("language", (string)null);

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            LangCode = "en",
                            LangEnglish = "English",
                            LangOwn = "English"
                        },
                        new
                        {
                            Id = (short)2,
                            LangCode = "de",
                            LangEnglish = "German",
                            LangOwn = "Deutsch"
                        });
                });

            modelBuilder.Entity("writings_backend_dotnet.Models.Like", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("lke", (string)null);
                });

            modelBuilder.Entity("writings_backend_dotnet.Models.LikeComment", b =>
                {
                    b.Property<long>("LikeId")
                        .HasColumnType("bigint")
                        .HasColumnName("likeId");

                    b.Property<long>("CommentId")
                        .HasColumnType("bigint")
                        .HasColumnName("comment_id");

                    b.HasKey("LikeId");

                    b.HasIndex("CommentId");

                    b.HasIndex("LikeId", "CommentId")
                        .IsUnique();

                    b.ToTable("like_comment", (string)null);
                });

            modelBuilder.Entity("writings_backend_dotnet.Models.LikeNote", b =>
                {
                    b.Property<long>("LikeId")
                        .HasColumnType("bigint")
                        .HasColumnName("likeId");

                    b.Property<long>("NoteId")
                        .HasColumnType("bigint")
                        .HasColumnName("note_id");

                    b.HasKey("LikeId");

                    b.HasIndex("NoteId");

                    b.HasIndex("LikeId", "NoteId")
                        .IsUnique();

                    b.ToTable("like_note", (string)null);
                });

            modelBuilder.Entity("writings_backend_dotnet.Models.Note", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("VerseId")
                        .HasColumnType("integer")
                        .HasColumnName("verse_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("VerseId");

                    b.ToTable("note", (string)null);
                });

            modelBuilder.Entity("writings_backend_dotnet.Models.Notification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .HasColumnType("text")
                        .HasColumnName("entity_type");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("notification_type");

                    b.Property<Guid>("RecipientId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipient_id");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.HasIndex("RecipientId");

                    b.ToTable("notification", (string)null);
                });

            modelBuilder.Entity("writings_backend_dotnet.Models.RequestLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(126)
                        .HasColumnType("character varying(126)");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(126)
                        .HasColumnType("character varying(126)");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("OccurredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("request_logs", (string)null);
                });

            modelBuilder.Entity("writings_backend_dotnet.Models.Role", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role_name");

                    b.HasKey("Id");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("role", (string)null);

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            RoleName = "Admin"
                        },
                        new
                        {
                            Id = (short)2,
                            RoleName = "Verified"
                        });
                });

            modelBuilder.Entity("writings_backend_dotnet.Models.Root", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Latin")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("Own")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<short>("ScriptureId")
                        .HasColumnType("smallint")
                        .HasColumnName("scripture_id");

                    b.HasKey("Id");

                    b.HasIndex("ScriptureId");

                    b.HasIndex("Latin", "ScriptureId")
                        .IsUnique();

                    b.ToTable("root", (string)null);
                });

            modelBuilder.Entity("writings_backend_dotnet.Models.Scripture", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<short>("Number")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("scripture", (string)null);
                });

            modelBuilder.Entity("writings_backend_dotnet.Models.ScriptureMeaning", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<short>("LanguageId")
                        .HasColumnType("smallint")
                        .HasColumnName("language_id");

                    b.Property<string>("Meaning")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<short>("ScriptureId")
                        .HasColumnType("smallint")
                        .HasColumnName("scripture_id");

                    b.HasKey("Id");

                    b.HasIndex("ScriptureId");

                    b.HasIndex("LanguageId", "ScriptureId")
                        .IsUnique();

                    b.ToTable("scripture_meaning", (string)null);
                });

            modelBuilder.Entity("writings_backend_dotnet.Models.Section", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("section_name");

                    b.Property<short>("Number")
                        .HasColumnType("smallint")
                        .HasColumnName("section_number");

                    b.Property<short>("ScriptureId")
                        .HasColumnType("smallint")
                        .HasColumnName("scripture_id");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ScriptureId", "Number")
                        .IsUnique();

                    b.ToTable("section", (string)null);
                });

            modelBuilder.Entity("writings_backend_dotnet.Models.SectionMeaning", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<short>("LanguageId")
                        .HasColumnType("smallint");

                    b.Property<string>("Meaning")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<short>("SectionId")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("SectionId");

                    b.HasIndex("LanguageId", "SectionId")
                        .IsUnique();

                    b.ToTable("section_meaning", (string)null);
                });

            modelBuilder.Entity("writings_backend_dotnet.Models.Session", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ExpiresAt")
                        .IsRequired()
                        .HasColumnType("timestamp")
                        .HasColumnName("expires_at");

                    b.Property<string>("SessionData")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("session");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("session", (string)null);
                });

            modelBuilder.Entity("writings_backend_dotnet.Models.Suggestion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("SuggestionText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("TranslationTextId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TranslationTextId");

                    b.HasIndex("UserId", "TranslationTextId")
                        .IsUnique();

                    b.ToTable("suggestion", (string)null);
                });

            modelBuilder.Entity("writings_backend_dotnet.Models.Translation", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("added_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("EagerFrom")
                        .HasColumnType("timestamp")
                        .HasColumnName("eager_from");

                    b.Property<short>("LanguageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("language_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("translation_name");

                    b.Property<DateTime?>("ProductionTime")
                        .HasColumnType("timestamp")
                        .HasColumnName("production_year");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.ToTable("translation", (string)null);
                });

            modelBuilder.Entity("writings_backend_dotnet.Models.TranslationText", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<short>("TranslationId")
                        .HasColumnType("smallint")
                        .HasColumnName("translation_id");

                    b.Property<int>("VerseId")
                        .HasColumnType("int")
                        .HasColumnName("verse_id");

                    b.HasKey("Id");

                    b.HasIndex("TranslationId");

                    b.HasIndex("VerseId");

                    b.ToTable("translation_text", (string)null);
                });

            modelBuilder.Entity("writings_backend_dotnet.Models.Translator", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1500)
                        .HasColumnType("varchar(1500)")
                        .HasColumnName("description");

                    b.Property<short>("LanguageId")
                        .HasColumnType("smallint")
                        .HasColumnName("language_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("translator_name");

                    b.Property<string>("Url")
                        .HasMaxLength(1500)
                        .HasColumnType("varchar(1500)");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.ToTable("translators", (string)null);
                });

            modelBuilder.Entity("writings_backend_dotnet.Models.TranslatorTranslation", b =>
                {
                    b.Property<short>("TranslatorId")
                        .HasColumnType("smallint")
                        .HasColumnName("translator_id");

                    b.Property<short>("TranslationId")
                        .HasColumnType("smallint")
                        .HasColumnName("translation_id");

                    b.Property<DateTime>("AssignedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("assigned_on")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("TranslatorId", "TranslationId");

                    b.HasIndex("TranslationId");

                    b.ToTable("translator_translation", (string)null);
                });

            modelBuilder.Entity("writings_backend_dotnet.Models.Transliteration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<short>("LanguageId")
                        .HasColumnType("smallint");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("varchar(1500)");

                    b.Property<int>("VerseId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("VerseId");

                    b.ToTable("transliterations", (string)null);
                });

            modelBuilder.Entity("writings_backend_dotnet.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Biography")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("EmailVerified")
                        .HasColumnType("timestamp");

                    b.Property<string>("Gender")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<DateTime?>("IsFrozen")
                        .HasColumnType("timestamp")
                        .HasColumnName("is_frozen");

                    b.Property<DateTime?>("IsPrivate")
                        .HasColumnType("timestamp")
                        .HasColumnName("is_private");

                    b.Property<DateTime?>("LastActive")
                        .HasColumnType("timestamp")
                        .HasColumnName("last_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<short>("PreferredLanguageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("preferred_languageId");

                    b.Property<short?>("RoleId")
                        .HasColumnType("smallint")
                        .HasColumnName("role_id");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PreferredLanguageId");

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("writings_backend_dotnet.Models.Verse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChapterId")
                        .HasColumnType("integer");

                    b.Property<short>("Number")
                        .HasColumnType("smallint")
                        .HasColumnName("verse_number");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TextNoVowel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TextSimplified")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId", "Number")
                        .IsUnique();

                    b.ToTable("verse", (string)null);
                });

            modelBuilder.Entity("writings_backend_dotnet.Models.Word", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("RootId")
                        .HasColumnType("integer");

                    b.Property<short>("SequenceNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("sequence_number");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TextNoVowel")
                        .HasColumnType("text");

                    b.Property<string>("TextSimplified")
                        .HasColumnType("text");

                    b.Property<int>("VerseId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RootId");

                    b.HasIndex("VerseId");

                    b.HasIndex("SequenceNumber", "VerseId")
                        .IsUnique();

                    b.ToTable("word", (string)null);
                });

            modelBuilder.Entity("writings_backend_dotnet.Models.WordMeaning", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<short>("LanguageId")
                        .HasColumnType("smallint");

                    b.Property<string>("Meaning")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("word_meaning");

                    b.Property<long>("WordId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("WordId");

                    b.ToTable("word_meanings", (string)null);
                });

            modelBuilder.Entity("Follow", b =>
                {
                    b.HasOne("writings_backend_dotnet.Models.User", "Followed")
                        .WithMany("Followers")
                        .HasForeignKey("FollowedId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("writings_backend_dotnet.Models.User", "Follower")
                        .WithMany("Following")
                        .HasForeignKey("FollowerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Followed");

                    b.Navigation("Follower");
                });

            modelBuilder.Entity("FreezeR", b =>
                {
                    b.HasOne("writings_backend_dotnet.Models.User", "User")
                        .WithMany("FreezeRecords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("writings_backend_dotnet.Models.Block", b =>
                {
                    b.HasOne("writings_backend_dotnet.Models.User", "Blocked")
                        .WithMany("BlockedByUsers")
                        .HasForeignKey("BlockedId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("writings_backend_dotnet.Models.User", "Blocker")
                        .WithMany("BlockedUsers")
                        .HasForeignKey("BlockerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Blocked");

                    b.Navigation("Blocker");
                });

            modelBuilder.Entity("writings_backend_dotnet.Models.Chapter", b =>
                {
                    b.HasOne("writings_backend_dotnet.Models.Section", "Section")
                        .WithMany("Chapters")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Section");
                });

            modelBuilder.Entity("writings_backend_dotnet.Models.ChapterMeaning", b =>
                {
                    b.HasOne("writings_backend_dotnet.Models.Chapter", "Chapter")
                        .WithMany("Meanings")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("writings_backend_dotnet.Models.Language", "Language")
                        .WithMany("ChapterMeaning")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chapter");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("writings_backend_dotnet.Models.Collection", b =>
                {
                    b.HasOne("writings_backend_dotnet.Models.User", "User")
                        .WithMany("Collections")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("writings_backend_dotnet.Models.CollectionVerse", b =>
                {
                    b.HasOne("writings_backend_dotnet.Models.Collection", "Collection")
                        .WithMany("Verses")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("writings_backend_dotnet.Models.Verse", "Verse")
                        .WithMany("CollectionVerses")
                        .HasForeignKey("VerseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Collection");

                    b.Navigation("Verse");
                });

            modelBuilder.Entity("writings_backend_dotnet.Models.Comment", b =>
                {
                    b.HasOne("writings_backend_dotnet.Models.Comment", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("writings_backend_dotnet.Models.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentComment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("writings_backend_dotnet.Models.CommentNote", b =>
                {
                    b.HasOne("writings_backend_dotnet.Models.Comment", "Comment")
                        .WithOne("CommentNote")
                        .HasForeignKey("writings_backend_dotnet.Models.CommentNote", "CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("writings_backend_dotnet.Models.Note", "Note")
                        .WithMany("Comments")
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("Note");
                });

            modelBuilder.Entity("writings_backend_dotnet.Models.CommentVerse", b =>
                {
                    b.HasOne("writings_backend_dotnet.Models.Comment", "Comment")
                        .WithOne("CommentVerse")
                        .HasForeignKey("writings_backend_dotnet.Models.CommentVerse", "CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("writings_backend_dotnet.Models.Verse", "Verse")
                        .WithMany("Comments")
                        .HasForeignKey("VerseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("Verse");
                });

            modelBuilder.Entity("writings_backend_dotnet.Models.FootNote", b =>
                {
                    b.HasOne("writings_backend_dotnet.Models.FootNoteText", "FootNoteText")
                        .WithMany("FootNotes")
                        .HasForeignKey("FootNoteTextId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("writings_backend_dotnet.Models.TranslationText", "TranslationText")
                        .WithMany("FootNotes")
                        .HasForeignKey("TranslationTextId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FootNoteText");

                    b.Navigation("TranslationText");
                });

            modelBuilder.Entity("writings_backend_dotnet.Models.Like", b =>
                {
                    b.HasOne("writings_backend_dotnet.Models.User", "User")
                        .WithMany("Likes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("writings_backend_dotnet.Models.LikeComment", b =>
                {
                    b.HasOne("writings_backend_dotnet.Models.Comment", "Comment")
                        .WithMany("LikeComments")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("writings_backend_dotnet.Models.Like", "Like")
                        .WithOne("LikeComment")
                        .HasForeignKey("writings_backend_dotnet.Models.LikeComment", "LikeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("Like");
                });

            modelBuilder.Entity("writings_backend_dotnet.Models.LikeNote", b =>
                {
                    b.HasOne("writings_backend_dotnet.Models.Like", "Like")
                        .WithOne("LikeNote")
                        .HasForeignKey("writings_backend_dotnet.Models.LikeNote", "LikeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("writings_backend_dotnet.Models.Note", "Note")
                        .WithMany("LikeNotes")
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Like");

                    b.Navigation("Note");
                });

            modelBuilder.Entity("writings_backend_dotnet.Models.Note", b =>
                {
                    b.HasOne("writings_backend_dotnet.Models.User", "User")
                        .WithMany("Notes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("writings_backend_dotnet.Models.Verse", "Verse")
                        .WithMany("Notes")
                        .HasForeignKey("VerseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Verse");
                });

            modelBuilder.Entity("writings_backend_dotnet.Models.Notification", b =>
                {
                    b.HasOne("writings_backend_dotnet.Models.User", "Actor")
                        .WithMany("NotificationsSent")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("writings_backend_dotnet.Models.User", "Recipient")
                        .WithMany("NotificationsReceived")
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Recipient");
                });

            modelBuilder.Entity("writings_backend_dotnet.Models.Root", b =>
                {
                    b.HasOne("writings_backend_dotnet.Models.Scripture", "Scripture")
                        .WithMany("Roots")
                        .HasForeignKey("ScriptureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Scripture");
                });

            modelBuilder.Entity("writings_backend_dotnet.Models.ScriptureMeaning", b =>
                {
                    b.HasOne("writings_backend_dotnet.Models.Language", "Language")
                        .WithMany("ScriptureMeanings")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("writings_backend_dotnet.Models.Scripture", "Scripture")
                        .WithMany("Meanings")
                        .HasForeignKey("ScriptureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Scripture");
                });

            modelBuilder.Entity("writings_backend_dotnet.Models.Section", b =>
                {
                    b.HasOne("writings_backend_dotnet.Models.Scripture", "Scripture")
                        .WithMany("Sections")
                        .HasForeignKey("ScriptureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Scripture");
                });

            modelBuilder.Entity("writings_backend_dotnet.Models.SectionMeaning", b =>
                {
                    b.HasOne("writings_backend_dotnet.Models.Language", "Language")
                        .WithMany("SectionMeanings")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("writings_backend_dotnet.Models.Section", "Section")
                        .WithMany("Meanings")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("writings_backend_dotnet.Models.Session", b =>
                {
                    b.HasOne("writings_backend_dotnet.Models.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("writings_backend_dotnet.Models.Suggestion", b =>
                {
                    b.HasOne("writings_backend_dotnet.Models.TranslationText", "TranslationText")
                        .WithMany()
                        .HasForeignKey("TranslationTextId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("writings_backend_dotnet.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TranslationText");

                    b.Navigation("User");
                });

            modelBuilder.Entity("writings_backend_dotnet.Models.Translation", b =>
                {
                    b.HasOne("writings_backend_dotnet.Models.Language", "Language")
                        .WithMany("Translations")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("writings_backend_dotnet.Models.TranslationText", b =>
                {
                    b.HasOne("writings_backend_dotnet.Models.Translation", "Translation")
                        .WithMany("TranslationTexts")
                        .HasForeignKey("TranslationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("writings_backend_dotnet.Models.Verse", "Verse")
                        .WithMany("TranslationTexts")
                        .HasForeignKey("VerseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Translation");

                    b.Navigation("Verse");
                });

            modelBuilder.Entity("writings_backend_dotnet.Models.Translator", b =>
                {
                    b.HasOne("writings_backend_dotnet.Models.Language", "Language")
                        .WithMany("Translators")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("writings_backend_dotnet.Models.TranslatorTranslation", b =>
                {
                    b.HasOne("writings_backend_dotnet.Models.Translation", "Translation")
                        .WithMany("TranslatorTranslations")
                        .HasForeignKey("TranslationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("writings_backend_dotnet.Models.Translator", "Translator")
                        .WithMany("TranslatorTranslations")
                        .HasForeignKey("TranslatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Translation");

                    b.Navigation("Translator");
                });

            modelBuilder.Entity("writings_backend_dotnet.Models.Transliteration", b =>
                {
                    b.HasOne("writings_backend_dotnet.Models.Language", "Language")
                        .WithMany("Transliterations")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("writings_backend_dotnet.Models.Verse", "Verse")
                        .WithMany("Transliterations")
                        .HasForeignKey("VerseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Verse");
                });

            modelBuilder.Entity("writings_backend_dotnet.Models.User", b =>
                {
                    b.HasOne("writings_backend_dotnet.Models.Language", "PreferredLanguage")
                        .WithMany("PreferredUsers")
                        .HasForeignKey("PreferredLanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("writings_backend_dotnet.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PreferredLanguage");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("writings_backend_dotnet.Models.Verse", b =>
                {
                    b.HasOne("writings_backend_dotnet.Models.Chapter", "Chapter")
                        .WithMany("Verses")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chapter");
                });

            modelBuilder.Entity("writings_backend_dotnet.Models.Word", b =>
                {
                    b.HasOne("writings_backend_dotnet.Models.Root", "Root")
                        .WithMany("Words")
                        .HasForeignKey("RootId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("writings_backend_dotnet.Models.Verse", "Verse")
                        .WithMany("Words")
                        .HasForeignKey("VerseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Root");

                    b.Navigation("Verse");
                });

            modelBuilder.Entity("writings_backend_dotnet.Models.WordMeaning", b =>
                {
                    b.HasOne("writings_backend_dotnet.Models.Language", "Language")
                        .WithMany("WordMeanings")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("writings_backend_dotnet.Models.Word", "Word")
                        .WithMany("WordMeanings")
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Word");
                });

            modelBuilder.Entity("writings_backend_dotnet.Models.Chapter", b =>
                {
                    b.Navigation("Meanings");

                    b.Navigation("Verses");
                });

            modelBuilder.Entity("writings_backend_dotnet.Models.Collection", b =>
                {
                    b.Navigation("Verses");
                });

            modelBuilder.Entity("writings_backend_dotnet.Models.Comment", b =>
                {
                    b.Navigation("CommentNote");

                    b.Navigation("CommentVerse");

                    b.Navigation("LikeComments");

                    b.Navigation("Replies");
                });

            modelBuilder.Entity("writings_backend_dotnet.Models.FootNoteText", b =>
                {
                    b.Navigation("FootNotes");
                });

            modelBuilder.Entity("writings_backend_dotnet.Models.Language", b =>
                {
                    b.Navigation("ChapterMeaning");

                    b.Navigation("PreferredUsers");

                    b.Navigation("ScriptureMeanings");

                    b.Navigation("SectionMeanings");

                    b.Navigation("Translations");

                    b.Navigation("Translators");

                    b.Navigation("Transliterations");

                    b.Navigation("WordMeanings");
                });

            modelBuilder.Entity("writings_backend_dotnet.Models.Like", b =>
                {
                    b.Navigation("LikeComment");

                    b.Navigation("LikeNote");
                });

            modelBuilder.Entity("writings_backend_dotnet.Models.Note", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("LikeNotes");
                });

            modelBuilder.Entity("writings_backend_dotnet.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("writings_backend_dotnet.Models.Root", b =>
                {
                    b.Navigation("Words");
                });

            modelBuilder.Entity("writings_backend_dotnet.Models.Scripture", b =>
                {
                    b.Navigation("Meanings");

                    b.Navigation("Roots");

                    b.Navigation("Sections");
                });

            modelBuilder.Entity("writings_backend_dotnet.Models.Section", b =>
                {
                    b.Navigation("Chapters");

                    b.Navigation("Meanings");
                });

            modelBuilder.Entity("writings_backend_dotnet.Models.Translation", b =>
                {
                    b.Navigation("TranslationTexts");

                    b.Navigation("TranslatorTranslations");
                });

            modelBuilder.Entity("writings_backend_dotnet.Models.TranslationText", b =>
                {
                    b.Navigation("FootNotes");
                });

            modelBuilder.Entity("writings_backend_dotnet.Models.Translator", b =>
                {
                    b.Navigation("TranslatorTranslations");
                });

            modelBuilder.Entity("writings_backend_dotnet.Models.User", b =>
                {
                    b.Navigation("BlockedByUsers");

                    b.Navigation("BlockedUsers");

                    b.Navigation("Collections");

                    b.Navigation("Comments");

                    b.Navigation("Followers");

                    b.Navigation("Following");

                    b.Navigation("FreezeRecords");

                    b.Navigation("Likes");

                    b.Navigation("Notes");

                    b.Navigation("NotificationsReceived");

                    b.Navigation("NotificationsSent");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("writings_backend_dotnet.Models.Verse", b =>
                {
                    b.Navigation("CollectionVerses");

                    b.Navigation("Comments");

                    b.Navigation("Notes");

                    b.Navigation("TranslationTexts");

                    b.Navigation("Transliterations");

                    b.Navigation("Words");
                });

            modelBuilder.Entity("writings_backend_dotnet.Models.Word", b =>
                {
                    b.Navigation("WordMeanings");
                });
#pragma warning restore 612, 618
        }
    }
}
